### ISSUE TITLE
Доробки

### ISSUE THREAD

**Issue by SyntheticDream** [Salipon/flask-blog#1]
1. Створи в корні репозиторію файл `.gitignore`. Додай туди вміст з  https://www.toptal.com/developers/gitignore/api/python,pycharm+all,venv,visualstudiocode,linux,windows
2. Додай `app.config['SESSION_TYPE'] = 'filesystem'` на 9ту строку файлу `app.py`
   - будемо сподіватися, що це пофіксить твою помилку.
3. Видали папки `.vscode` та `__pychache__` та файл `database.db` з репозиторію, але не з файлової системи. Підказка -- `git rm --cached file1.txt`

**Comment by Salipon** [comment]
done
